### ISSUE TITLE
Get an image from id3 tag [feature request]

### ISSUE THREAD

**Issue by Gerlie15** [ben-xo/dir2cast#13]
Hi.
Is there any possibilty to implement this feature: get image from id3 tag if there is one.

Possible implementation:
If there is an image in mp3 tag, save it in the same folder as mp3 file with name: mp3_filename.jpg
and if there is an image with name: "mp3_filename.jpg" insert it in podcast item, otherwise take image,jpg (default podcast image).

I don't have the knowledge to do it so any help would be much appreciated!

**Comment by RobertBozic** [comment]
Dear Ben, good day to you!
Proposal and request:
1.
The correct code at line around 681 to 687 is: 
(sorry for mistake in my previous post)
`public function http_headers()
	{
		header('Content-type: text/xml; charset=UTF-8');
		header('Last-modified: ' . $this->getLastBuildDate());
	}`
2. 
We also have problems with images in item section of podcast:
Images are written with full filesystem path, instead of url:
`<item>
xxxxxx
<itunes:image href="/var/www/users/show/www/show1/show_1.jpg"/>
xxxxxx
xxxxxx
<pubDate>Tue, 06 Mar 2018 12:22:22 +0000</pubDate>
xxxxx
<image>/var/www/users/show/www/show1/show_1.jpg</image>
</item>`

Thanks, have a good day!

**Comment by ben-xo** [comment]
@RobertBozic can you raise those as two separate bugs?

**Comment by RobertBozic** [comment]
OK, thanks I will open two separate issues...

**Comment by ben-xo** [comment]
I have (finally) got round to implementing this!

**Comment by ben-xo** [comment]
@Gerlie15  @RobertBozic I'd be delighted if you could try out the feature!
