### ISSUE TITLE
Include all mp3's

### ISSUE THREAD

**Issue by Mrensmo** [ben-xo/dir2cast#23]
Love this little program! 

So far I'm just trying it out. And I'm wondering about "Number of items to show in the feed" with defaults to 10. I would want it to include all the MP3's in the folder. Is that possible in some way? Otherwise see this as a feature request. 

Mattias in Sweden

**Comment by ben-xo** [comment]
Hi @Mrensmo ! 

I would suggest you just set ITEM_COUNT to something very large, for example 1000000000 (1 billion). Even if you add 1 MP3 per minute, it will take you almost 2000 years to reach that limit.

**Comment by ben-xo** [comment]
i've created a new branch - https://github.com/ben-xo/dir2cast/tree/feature/cache-id3-data-per-file - which caches the data from scanned files much better, so you can create very large feeds much more easily (as it will scan new files incrementally instead of rescanning all files every time). Please can you help me test @Mrensmo  ?

**Comment by ben-xo** [comment]
This is now integrated since v1.20

**Comment by Mrensmo** [comment]
HI, back from the dead... 
It caches much better now but i got a new error. I will make a separate issue about that. 

Thnks!
