### ISSUE TITLE
default item title to mp3 filename if no id3 tag

### ISSUE THREAD

**Issue by wesyah234** [ben-xo/dir2cast#38]
Love this script, works great.  However, I tried it on some mp3 files that apparently don't have any id3 tag info to use as the title, so I see (untitled) in the <title> tag.  At least I assume that's why it's happening.  Any way you could fall back to using the filename of the mp3 file instead? At least there would be something to display then in my podcast player. Thanks!!

**Comment by ben-xo** [comment]
Yeah, probably a good idea. Thanks for the suggestion!

You definitely won't get the most out of dir2cast unless you tag your files, but I suppose there are lots of use-cases for it which aren't just straight-up publishing a podcast…

**Comment by ben-xo** [comment]
Have a look at https://github.com/ben-xo/dir2cast/pull/40 and see if this suits your needs?

**Comment by wesyah234** [comment]
Perfect, I tried it and it works just as I expected. The only tweak I might suggest, if you have time, would be to strip the .mp3 extension as everything is an mp3 file anyway. Thank you for the quick attention to this!!

**Comment by ben-xo** [comment]
I'd rather not go down the route of having dir2cast try to "interpret" filenames - I like the idea of using the filename as a placeholder (because it's more useful than "(untitled)"), but really the idea was that for most people if you're seeing that it means you need to fix the tags in your feed. Where to stop - replacing underscores with spaces? Trying to parse artist and title? (Besides, we support mp3, m4a and mp4 at the moment, so it could technically be ambiguous if you happen to have several formats with the same filename).

If you want to branch to make this work for your needs, though, the place you need to edit is `RSS_File_Item::getTitle()`.

**Comment by wesyah234** [comment]
yeah, no problem, I understand! This fix is great just the way it is.  I also noticed that the podcast title is interpreted from the directory name when using the dir= option which is great, this works for me.Thank you.
