### ISSUE TITLE
Suggestion: clear cache when count of mp3 files in directory != count in feed

### ISSUE THREAD

**Issue by wesyah234** [ben-xo/dir2cast#39]
I was uploading mp3 files with older timestamps, and the cache was not clearing.  I 'touched' the mp3 file and this caused the cache to clear.  Perhaps you could count the files in the feed and compare to the files in the directory and if not equal, just clear the cache. Thanks!

**Comment by ben-xo** [comment]
This can definitely be done and shouldn't impact my use case to do, but may I ask how you're uploading files with old timestamps / what your use case is here?

**Comment by wesyah234** [comment]
Sure.  If you have some of your own mp3 files with old timestamps and you want to upload them to your personal feed, it will work one time, but once the cache is established, you can't upload any new mp3s.  I find podcast feeds are very handy for getting personal music files onto various devices (apple and android, tablets and phones), without having to deal with itunes on apple or various syncing options for getting music into android devices.

**Comment by ben-xo** [comment]
Right, so you've dropped dir2cast into a folder of stuff you already had, rather than uploading mp3s ('episode by episode') to a folder where you're publishing a podcast?

What OS? Linux?

I'm not sure if I want to track the file count anywhere as that's a new piece of information to keep track of. It's all based on the 'mtime' of episode files at the moment - most people are using this to detect when a new podcast episode has been uploaded to a remote server.

you can, of course, use scp or rsync without having it preserve timestamps.

**Comment by wesyah234** [comment]
Yes, I can change my processes as needed to get the timestamp detection to work properly, no need to change anything major. Thank you!
